### ISSUE TITLE
PS7 - Wordcloud and normalize_tokens

### ISSUE THREAD

**Issue by fjd119** [abjer/tsds2018#10]
Hi.
When I try installing wordcloud via conda the following issue arises:

from wordcloud import Wordcloud
ImportError                               Traceback (most recent call last)
<ipython-input-290-166dc8c3e6ee> in <module>()
----> 1 from wordcloud import Wordcloud

~\Anaconda3\lib\site-packages\wordcloud\__init__.py in <module>()
----> 1 from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
      2                         get_single_color_func)
      3 from .color_from_image import ImageColorGenerator
      4 
      5 __all__ = ['WordCloud', 'STOPWORDS', 'random_color_func',

~\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in <module>()
     17 from operator import itemgetter
     18 
---> 19 from PIL import Image
     20 from PIL import ImageColor
     21 from PIL import ImageDraw

~\Anaconda3\lib\site-packages\PIL\Image.py in <module>()
     54     # Also note that Image.core is not a publicly documented interface,
     55     # and should be considered private and subject to change.
---> 56     from . import _imaging as core
     57     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     58         raise ImportError("The _imaging extension was built for another "

ImportError: DLL load failed: Det angivne modul blev ikke fundet."

Also, when using the normalize_token function the following error shows up:

"
AttributeError                            Traceback (most recent call last)
<ipython-input-292-bb73ccf7a047> in <module>()
      4 nltk.download('stopwords')
      5 stopwords = stopwords.words('english')
----> 6 stop_words = set(stopwords.words('english')) # remember to define as set for performance
      7 # #The stemmers and lemmers need to be initialized before being run
      8 porter = nltk.stem.porter.PorterStemmer()

AttributeError: 'list' object has no attribute 'words'
"
Has anybody experienced something similar or do anybody have an idea of what to do?

Best

Anders Nielsen

**Comment by EmilToftHansen** [comment]
Hi Anders

Yes, I did also struggle to get the wordcloud module to function and I had (among others) the same issue as you are referring to. I solved it by following this SE answer:

https://stackoverflow.com/a/43804968

However, i'm pretty sure that this is not the best way to solve it (see for instance this thread: https://github.com/python-pillow/Pillow/issues/3019)

Regards
Emil TH

**Comment by snorreralund** [comment]
In relation to your AttributeError - the stopword line- change line 5 to:
stopwords = set(stopwords.words('english'))

and throw out linenumber 6.
