### ISSUE TITLE
Ex. 7.1.3

### ISSUE THREAD

**Issue by kazuyanagimoto** [abjer/tsds2018#14]
I am confusing the meaning of ex. 7.1.3.

7.1.3. 
What data source should we extract zip-codes from? From sentiment_df.review_text? If so, I couldn't find any zip-code in the reviews and I couldn't imagine anyone's writing any zip-code in his/her review. Am I misunderstanding this question?

**Comment by snorreralund** [comment]
I thought that it would be easier for you to not change dataset. Indeed the zipcode was more relevant in the Enron dataset, however I did find some zipcodes in the reviews also.

**Comment by kazuyanagimoto** [comment]
Thank you for your answer.
I noticed my mistake in regex and eventually I've succeed to extract zip-code even from sentiment_df.
