### ISSUE TITLE
Run time for sentiment analyses?

### ISSUE THREAD

**Issue by JonathanIsakMarin** [abjer/tsds2018#15]
In exc. 7.3.1 we are asked to do sentiment analysis with different packages. 

The sentiment_df dataset is apr. 72.000 observations/reviews. I'm experiencing very very long run times for all packages when trying to run the analyses over the entire dataset...

Are we supposed to use the whole dataset or can we i.e. just extract a random subset of 5000 observations and use that for our sentiment analyses?

**Comment by snorreralund** [comment]
In cases with large datasets it is always good to first run your analysis on a small subset of the data, and then run the whole thing over night. But I will allow both answers.

**Comment by JonathanIsakMarin** [comment]
Cool. Thank you!
