### ISSUE TITLE
Exercise 8.3.1

### ISSUE THREAD

**Issue by KristianLN** [abjer/tsds2018#16]
Hi

Exercise 8.3.1 says initially; _Retrain your model on all of your data_
Does that imply that we should handle the task as a multi-class classification problem or that we shouldn't split the binary data set up into train/test?

Best regards,

Kristian Lunow Nielsen

**Comment by ulfaslak** [comment]
**Better late then never**: The latter. The idea is that after training it on all data including heroes and villains you can predict whether amb. characters are more like heroes or villains.
