### ISSUE TITLE
Installing "afinn" with Anaconda?

### ISSUE THREAD

**Issue by nicolaivinther** [abjer/tsds2018#17]
Can anyone help me with installing "afinn" in my Anaconda environment? I currently have it installed for my normal Python 3, but I am having trouble getting it to work for Anaconda.
I have used the following commands without succes:

```
conda install afinn
sudo conda install afinn
sudo conda install -c anaconda afinn
```

Always getting this error:

> "PackagesNotFoundError: The following packages are not available from current channels:"

Thank you

**Comment by ulfaslak** [comment]
You can't install it with the `conda` package manager. But you can install it with the version of `pip` that comes with anaconda. For me, the path to `pip` is `/Users/ulfaslak/anaconda3/bin/pip`, and so I could run `sudo /Users/ulfaslak/anaconda3/bin/pip install afinn` to get Afinn installed in my Anaconda distribution of Python.

**Comment by nicolaivinther** [comment]
Beautiful, it works!
Thanks a lot.
