### ISSUE TITLE
Ex. 3.5.1: Getting NameError

### ISSUE THREAD

**Issue by ulfaslak** [abjer/tsds2018#2]
I try to run the code

```
for i in range(4):
    print(a[i])
```

But I get a NameError

**Comment by ErasmiosCode** [comment]
Answer

**Comment by Polichinel** [comment]
Well...

**Comment by Krier** [comment]
Something, somethng false

**Comment by elben10** [comment]
`a` is not defined

**Comment by ulfaslak** [comment]
AMAZING! That solved my problem. I'm closing this one.

**(Remember to close the issue when someone solved your problem.)**
