### ISSUE TITLE
Issues with retrieving Marvel data

### ISSUE THREAD

**Issue by JonathanIsakMarin** [abjer/tsds2018#3]
Hi everyone!

I'm trying to get the marvel data for the network excercises using the code in the repository. 

However, when i run the code it returns the following error: 

`FileNotFoundError: [WinError 3] Den angivne sti blev ikke fundet: 'villains'`

I've tried to run the code on different computers but it returns the same error every time.

Any suggestions? :-)

**Comment by abjer** [comment]
The error message seems indicate that the local path 'villains' is not created within the current directory where you execute the code. 

Can you paste your code?

**Comment by JonathanIsakMarin** [comment]
Yes, just copied it from the folder: 

`import requests as rq
import json, re, os

def get_list_of_chars(cla):
    """Input 'heroes' or 'villains' and return list of characters."""
    # Format query
    endpoint = "https://en.wikipedia.org/w/api.php?"
    action = "action=query"
    _list = "list=categorymembers"
    _format = "format=json"
    cmtitle = "cmtitle=Category:Marvel_Comics_super%s" % cla
    cmlimit = "cmlimit=500"
    cmcontinue = ""

    characters = []
    while True:
        query_url = "&".join([endpoint, action, _list, cmtitle, _format, cmlimit, cmcontinue])
        data = rq.get(query_url, headers={'User-agent': 'ulfs bot'}).json()
        characters.extend([(c['title'], c['pageid']) for c in data['query']['categorymembers']])
        
        if 'continue' not in data:
            break
        
        cmcontinue = 'cmcontinue=' + data['continue']['cmcontinue']

    return characters

# Extract lists of characters
superheroes = get_list_of_chars('heroes')
supervillains = get_list_of_chars('villains')

# Download their page markup
for c in set(superheroes) | set(supervillains):
    
    # Get the faction of the character
    if c in superheroes and c in supervillains:
        folder = "ambiguous"
    elif c in superheroes:
        folder = "heroes"
    elif c in supervillains:
        folder = "villains"
    
    # Only download new pages
    if c[0] + ".txt" in os.listdir('%s' % folder):
        continue

    # Replace slash with dash (one character has a "/" in their name)
    if "/" in c[0]:
        c = (c[0].replace("/", "-"), c[1])
    
    # Get the data
    data = rq.get(
        "https://en.wikipedia.org/w/api.php?&prop=revisions&rvprop=content&action=query&pageids=%d&format=json" % c[1]
    ).json()
    
    # Get the markup
    markup = data['query']['pages'].values()[0]['revisions'][0]['*']
    
    # Save it
    with open("%s/%s.txt" % (folder, c[0]), 'w') as fp:
        fp.write(markup.encode('utf-8'))`

**Comment by JonathanIsakMarin** [comment]
`import requests as rq
import json, re, os

def get_list_of_chars(cla):
    """Input 'heroes' or 'villains' and return list of characters."""
    # Format query
    endpoint = "https://en.wikipedia.org/w/api.php?"
    action = "action=query"
    _list = "list=categorymembers"
    _format = "format=json"
    cmtitle = "cmtitle=Category:Marvel_Comics_super%s" % cla
    cmlimit = "cmlimit=500"
    cmcontinue = ""

    characters = []
    while True:
        query_url = "&".join([endpoint, action, _list, cmtitle, _format, cmlimit, cmcontinue])
        data = rq.get(query_url, headers={'User-agent': 'ulfs bot'}).json()
        characters.extend([(c['title'], c['pageid']) for c in data['query']['categorymembers']])
        
        if 'continue' not in data:
            break
        
        cmcontinue = 'cmcontinue=' + data['continue']['cmcontinue']

    return characters

# Extract lists of characters
superheroes = get_list_of_chars('heroes')
supervillains = get_list_of_chars('villains')

# Download their page markup
for c in set(superheroes) | set(supervillains):
    
    # Get the faction of the character
    if c in superheroes and c in supervillains:
        folder = "ambiguous"
    elif c in superheroes:
        folder = "heroes"
    elif c in supervillains:
        folder = "villains"
    
    # Only download new pages
    if c[0] + ".txt" in os.listdir('%s' % folder):
        continue

    # Replace slash with dash (one character has a "/" in their name)
    if "/" in c[0]:
        c = (c[0].replace("/", "-"), c[1])
    
    # Get the data
    data = rq.get(
        "https://en.wikipedia.org/w/api.php?&prop=revisions&rvprop=content&action=query&pageids=%d&format=json" % c[1]
    ).json()
    
    # Get the markup
    markup = data['query']['pages'].values()[0]['revisions'][0]['*']
    
    # Save it
    with open("%s/%s.txt" % (folder, c[0]), 'w') as fp:
        fp.write(markup.encode('utf-8'))`

**Comment by JonathanIsakMarin** [comment]
Just copied straight from here: 
https://github.com/abjer/tsds/blob/master/data/marvel_dataset/get_data.py

**Comment by abjer** [comment]
My guess is that you the code used in a new directory and that you hadn't created subfolders that with the names that Ulf used. So either you make the folders yourself or you use the updated script (I have just pushed a fix).

**Comment by ulfaslak** [comment]
Ah, yes, just change the paths and then it will work.
