### ISSUE TITLE
Help with making a 2d grid

### ISSUE THREAD

**Issue by abjer** [abjer/tsds2018#5]
Can anyone help me with making a 2d grid of evenly spaced points with fixed distance? The grid must me bounded on the x-axis by the values `minx`, `maxx` and on the y-axis by values `miny`, `maxy`. The grid points must have the distance `dist` between each point.

I will reward the first and the best answer with a beer!

**Comment by AVibel** [comment]
One suggestion is

`import numpy as np`
`bounds = municipalities_sl.total_bounds`
`dist=500`
`y, x = grid_points = np.mgrid[bounds[1]:bounds[3]:dist, bounds[0]:bounds[2]:dist]`

To get x and y in one dimensiton use:
`x.flatten()`
`y.flatten()`

**Comment by abjer** [comment]
Thanks, that helped, a beer coming your way 👍. And so what are these `x` and `y` values?

Are there any more answers?

**Comment by abjer** [comment]
Has anyone tried the option of using a list comprehension of two lists, e.g. called X and Y?

**Comment by AVibel** [comment]
The `x` and `y` is the east and north coordinates in the Danish CRS format (epsg=25832). Another way to get the same result is  by using a double for loop:

`dist=500`
`minx,miny,maxx,maxy = municipalities_sl.total_bounds.astype(int)`
`[(x,y) for x in range(minx,maxx,dist) for y in range(miny,maxy,dist)]`

This method is maybe more intuitive.

**Comment by elben10** [comment]
A much simpler solution (I think and much cleaner approach) would be to use the itertools library

```python
from itertools import product
from numpy import arange, array

def grid(minx, maxx, miny, maxy, dist):
    x_range = list(arange(minx, maxx, dist))
    y_range = list(arange(miny, maxy, dist))
    return array(list(product(x_range, y_range)))

grid(10, 20, 10.5, 20.3, 0.5)
```

**Comment by abjer** [comment]
Thanks for the answers @AVibel and @elben10 - I think both of your answers are really good so you both win a beer; formally you get it respectively for first and best answer.
