### ISSUE TITLE
assigment 1 Ex 2b.5.3 - Stations?

### ISSUE THREAD

**Issue by Polichinel** [abjer/tsds2018#7]
I am plugging in my old answers in assignment 1 and notice that I have not completed Ex 2b.5.3. In the dataset "data" I have the variable for the road names (road_name) and in the data set data_geo I have the coordinates for the stations. It seems clear to my that each road name correspond directly to a station (22 of the kind). So my question is this: is there any difference between "road" and "station" in 2b.5.3?

**Comment by abjer** [comment]
Yes, you should understand the question is referring to the road_name - thanks for the clarification.
